### ISSUE TITLE
Missing device info for HTC t6 (One Max) for building

### ISSUE THREAD

**Issue by FatherRandom** [LineageOS/lineage_wiki#17]
Hello and thanks for all the effort you put into LineageOS! 

I'm trying to build LineageOS 14.1 for an HTC One Max (t6 gsm) by using the instructions for the m8 but substituted device name (t6). I extracted the proprietary blobs from my phone and reran breakfast t6. However, I got error messages about missing device-specific information and maybe having the wrong manifest. 

Shall I just wait a couple of weeks for the required stuff to be transferred to the git repository or is the t6 not going to be supported? 

Any help or information is greatly appreciated!

**Comment by FatherRandom** [comment]
This is the output from breakfast t6:
`xxxxx@xxxx:~/android/system$ breakfast t6
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/htc/t6/lineage.mk]]: "vendor/qcom/binaries/msm8960/graphics/graphics-vendor.mk" does not exist.  Schluss.
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/htc/t6/lineage.mk]]: "vendor/qcom/binaries/msm8960/graphics/graphics-vendor.mk" does not exist.  Schluss.
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/htc/t6/lineage.mk]]: "vendor/qcom/binaries/msm8960/graphics/graphics-vendor.mk" does not exist.  Schluss.
Device t6 not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_htc_t6
Default revision: cm-14.1
Checking branch info
Checking if device/htc/t6 is fetched from android_device_htc_t6
LineageOS/android_device_htc_t6 already fetched to device/htc/t6
Syncing repository to retrieve project.
Fetching project LineageOS/android_device_htc_t6
Fetching projects: 100% (1/1), done.  

Repository synced!
Looking for dependencies in device/htc/t6
Looking for dependencies in device/htc/t6-common
Looking for dependencies in device/htc/msm8960-common
Looking for dependencies in device/qcom/common
Dependencies file not found, bailing out.
Done
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/htc/t6/lineage.mk]]: "vendor/qcom/binaries/msm8960/graphics/graphics-vendor.mk" does not exist.  Schluss.
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/htc/t6/lineage.mk]]: "vendor/qcom/binaries/msm8960/graphics/graphics-vendor.mk" does not exist.  Schluss.

** Don't have a product spec for: 'lineage_t6'
** Do you have the right repo manifest?
`

**Comment by zifnab06** [comment]
...this isn't the place for build problems.
